name: LeParty
version: 1.0.2
description: A party manager

author: Deku
website: http://deku.github.io
main: cl.josedev.LeParty.LeParty

commands:
    party:
        description: Party command
        usage: /party <option>
        alias: grupo
    partyadmin:
        description: Party Admin command
        usage: /partyadmin <option>
        alias: ptadmin
        
permissions:
    party.user:
        description: Permission for users
        default: true
    party.admin:
        description: Permission for admins
        default: op