name: WoWParty
version: 1.0.0
description: A party manager

author: Deku
website: http://www.github.com/Deku
main: cl.josedev.WoWParty.WoWParty

commands:
    party:
        description: Party command
        usage: /<command> <option>
        alias: pt
    partyadmin:
        description: Party admin command
        usage: /<command <option>
        alias: ptadmin
        
permissions:
    party.user:
        description: Permission for users
        default: true
    party.admin:
        description: Permission for admins
        default: op